### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by mattiaisgro** [elklein96/spotify-dl#1]
When i execute init.js as you told i get an error saying "Unhandled Error Event" at Event.js line 141 and an error with "spawning start".
![cattura](https://cloud.githubusercontent.com/assets/12460051/12094688/436175a0-b30a-11e5-9aab-de13172ebeec.PNG)

**Comment by elklein96** [comment]
Hello! Looks to me like you're running this on a Windows machine. Here are a few things to verify that all dependencies are correctly installed:
1. Execute `$ npm install` and `$ npm rebuild` to make sure all node modules are present.
2. Make sure that youtube-dl is correctly installed - this error is generated when an instance of youtube-dl does not execute.
   
   > An easy check is to execute the command `$ youtube-dl`. If correctly installed it will prompt you for an input URL. If it does not execute, [here is the source to install youtube-dl](https://rg3.github.io/youtube- dl/download.html).

**Comment by mattiaisgro** [comment]
All the commands you've listed work.
I dont know what's the problem here...

**Comment by elklein96** [comment]
To troubleshoot, please try running `$ node app.js` and then open your browser to [localhost:8888](http://localhost:8888)

**Comment by elklein96** [comment]
Fixed the issue and it is now up to date on Github. Let me know if it works! Thanks!

**Comment by mattiaisgro** [comment]
It doesnt work anyway.
I tried using directly app.js and it works. I can do all the stuff on localhost:8888.
But i paste in my playlist URL and it doesnt work. It says "Enter a valid Spotify playlist"...

**Comment by elklein96** [comment]
Make sure that the URL follows the format:

https://open.spotify.com/user/1247907770/playlist/7nsLGP561dAq8NVDY4K2fC, where '/user/' is followed by your user id and '/playlist/' is followed by the playlist id. 

I've tested it on OS X 10.8-10.11, Ubuntu Linux and Windows 7 & 8 and continues to work correctly for me. What OS are you using?

**Comment by mattiaisgro** [comment]
Im using Windows 10 :tired_face:
For the URL, i simply copied and pasted the one for sharing the playlist.
It is in the form you showed.

EDIT: Youre playlist works.
I should replace the username with the ID, now i try.

EDIT 2: How should i get my user ID? :dizzy_face:
Sorry for the stupid question.

**Comment by elklein96** [comment]
I just changed the regex for the URL checker and it's now on Github. Let me know if it works!

**Comment by mattiaisgro** [comment]
What a fast coder!

**Comment by mattiaisgro** [comment]
I have found about the user ID, in my case it isnt a number because i didnt login with Faebook.
Did you?

**Comment by mattiaisgro** [comment]
It works now, thank you!

**Comment by elklein96** [comment]
Yes, I logged in with Facebook, so my user ID was all digits and I only accounted for that in my URL verifier.

**Comment by elklein96** [comment]
Awesome! Thanks so much for helping me test!
